GET http://localhost:3001/convertir-png-a-webp?ruta=api/images/Jaden-TFSP.png


### fusion

POST http://localhost:3001/cards
Content-Type: application/json

{
    "names": [
        "Cyber Dragon",
        "Power Bond",
        "Future Fusion",
        "De-Fusion",
        "Blowback Dragon",
        "The Light - Hex-Sealed Fusion",
        "Cyber Twin Dragon",
        "Cyber End Dragon",
        "Proto-Cyber Dragon",
        "Mechanicalchaser",
        "Barrel Dragon",
        "The Fiend Megacyber",
        "Kinetic Soldier",
        "Machine Duplication",
        "Different Dimension Capsule",
        "Gatling Dragon",
        "Mechanical Hound",
        "Cyber Laser Dragon",
        "Cyber Phoenix",
        "Machine Conversion Factory",
        "Megasonic Eye",
        "Labyrinth Tank",
        "Pendulum Machine",
        "Giant Mech-Soldier",
        "Mech Bass",
        "Guardian of the Throne Room",
        "Disk Magician",
        "Royal Guard",
        "Slot Machine",
        "Steel Ogre Grotto 2",
        "Cyber-Tech Alligator",
        "Cyber Falcon",
        "Mighty Guard",
        "Cybernetic Cyclopean",
        "Cyber Archfiend",
        "System Down",
        "Cyber Barrier Dragon",
        "Photon Generator Unit",
        "Attack Reflector Unit",
        "Cyber Kirin"
    ],
    "pack": "technology-master"
}

### Tag Sruvivor

POST http://localhost:3001/cards
Content-Type: application/json

{
    "names": [
  "Snatch Steal",
  "Injection Fairy Lily",
"United We Stand",
"Mage Power",
"Exchange of the Spirit",
"Cyber-Stein",
"Brain Control",
"Creature Swap",
"Raigeki Break",
"Horus the Black Flame Dragon LV6",
"Horus the Black Flame Dragon LV8",
"Armed Dragon LV7",
"Ancient Gear Golem",
"Ultimate Insect LV7",
"Ancient Gear Castle",
"Magical Arm Shield",
"Soul Exchange",
"Enemy Controller",
"Final Countdown",
"Horus the Black Flame Dragon LV4",
"Armed Dragon LV3",
"Armed Dragon LV5",
"Level Up!",
"Silent Magician LV4",
"Silent Magician LV8",
"Ultimate Insect LV3",
"Ultimate Insect LV5",
"Ancient Gear Beast",
"Level Modulation",
"Armed Dragon LV10",
"Mind Control",
"Statue of the Wicked",
"Dark Coffin",
"Judgment of Pharaoh",
"Yu-Jo Friendship",
"Unity",
"Ultimate Insect LV1",
"Dark Mimic LV1",
"Dark Mimic LV3",
"The Graveyard in the Fourth Dimension",
"Covering Fire",
"Owner's Seal",
"Union Attack",
"Ancient Gear Soldier",
"Gift of the Martyr",
"Double Attack",
"Ancient Gear",
"Magnet Circle LV2",
"Ancient Gear Factory",
"Ancient Gear Drill",
"Damage Condenser",
"Ancient Gear Cannon"
],
    "pack": "tag-survivor"
}

### First Monster

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Blue-Eyes White Dragon",
    "Summoned Skull",
    "Dark Magician",
    "Red-Eyes B. Dragon",
    "Gaia The Fierce Knight",
    "Giant Soldier of Stone",
    "Millennium Shield",
    "Oppressed People",
    "D.D. Trainer",
    "Gogiga Gagagigo",
    "Neo Aqua Madoor",
    "Curse of Dragon",
    "Aqua Madoor",
    "Prevent Rat",
    "Ushi Oni",
    "Island Turtle",
    "Earthbound Spirit",
    "Inpachi",
    "People Running About",
    "United Resistance",
    "Acrobat Monkey",
    "Skull Dog Marron",
    "Shadow Specter",
    "Beaver Warrior",
    "Saggi the Dark Clown",
    "Griffore",
    "Torike",
    "Big Insect",
    "Giant Flea",
    "Mammoth Graveyard",
    "Wolf",
    "Kojikocy",
    "Jellyfish",
    "Uraby",
    "King of Yamimakai",
    "Sleeping Lion",
    "Dark Plant",
    "The 13th Grave",
    "The Judgement Hand",
    "Ancient Jar",
    "Dark King of the Abyss",
    "Turtle Tiger",
    "Water Omotics",
    "Ancient Tree of Enlightenment",
    "Tao the Chanter",
    "Change Slime",
    "Toon Alligator",
    "Dark Rabbit",
    "Blocker",
    "Golgoil",
    "Kappa Avenger",
    "Destroyer Golem",
    "Garvas",
    "Kattapillar",
    "Fungi of the Musk",
    "Laughing Flower",
    "Bean Soldier",
    "Bone Mouse",
    "Yormungarde",
    "Pale Beast",
    "Ancient Lizard Warrior",
    "Red Archery Girl",
    "Grand Tiki Elder",
    "Melchid the Four-Face Beast",
    "Souls of the Forgotten",
    "The Portrait's Secret"
  ],
  "pack": "first-monster"
}



### First Fusion

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Polymerization",
    "Fusion Sage",
    "Summoner of Illusions",
    "Flame Swordsman",
    "Monster Eye",
    "Punished Eagle",
    "Rose Spectre of Dunn",
    "Ryu-Kishin",
    "Feral Imp",
    "Tyhone",
    "Karbonala Warrior",
    "Hercules Beetle",
    "Silver Fang",
    "Man-Eating Plant",
    "Barox",
    "Mystic Horseman",
    "Rabid Horseman",
    "Wings of Wicked Flame",
    "Charubin the Fire Knight",
    "Flame Manipulator",
    "Temple of Skulls",
    "Rhaimundos of the Red Sword",
    "Firegrass",
    "M-Warrior #1",
    "Darkfire Dragon",
    "Armaill",
    "Fusionist",
    "Petit Dragon",
    "Petit Angel",
    "Hinotama Soul",
    "Rare Fish",
    "Beautiful Headhuntress",
    "Enchanting Mermaid",
    "Mavelus",
    "Ground Attacker Bugroth",
    "Protector of the Throne",
    "Mystical Sheep 2",
    "Fireyarou",
    "Dragoness the Wicked Knight",
    "One-Eyed Shield Dragon",
    "Sonic Maid",
    "Giltia the D. Knight",
    "Ocubeam",
    "Metal Dragon",
    "Deepsea Shark",
    "Defender of the Sea",
    "Kaminari Attack",
    "Vermillion Sparrow",
    "Kuwagata Alpha",
    "Pragtical",
    "Flower Wolf",
    "Skullbird",
    "Kwagar Hercules",
    "Mega Thunderball",
    "Niwatori",
    "Tongyo",
    "Behegon",
    "Steel Ogre Grotto 1",
    "Lesser Dragon",
    "Darkworld Thorns",
    "Trakadon",
    "Takuhee",
    "Marine Beast",
    "Warrior of Tradition",
    "Blue-Winged Crown",
    "Amphibious Bugroth",
    "Flame Viper",
    "The Gross Ghost of Fled Dreams",
    "Headless Knight",
    "The Earl of Demise",
    "Gigobyte",
    "Fiend Scorpion",
    "Goblin Calligrapher"
  ],
  "pack": "first-fusion"
}


### First Effect Monster

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Sangan",
    "Kaibaman",
    "Dark Eradicator Warlock",
    "Time Wizard",
    "Kuriboh",
    "D.D. Warrior",
    "Dark Magician Girl",
    "Ancient Lamp",
    "White Magical Hat",
    "Pinch Hopper",
    "Sword Hunter",
    "Wall of Illusion",
    "Buster Blader",
    "Gearfried the Iron Knight",
    "Hayabusa Knight",
    "Cat's Ear Tribe",
    "Hyper Hammerhead",
    "Prickle Fairy",
    "Swamp Battleguard",
    "Crass Clown",
    "Dream Clown",
    "Tainted Wisdom",
    "Penguin Knight",
    "Wodan the Resident of the Forest",
    "The Little Swordsman of Aile",
    "Jirai Gumo",
    "Zone Eater",
    "Steel Scorpion",
    "Swordsman from a Foreign Land",
    "Cockroach Knight",
    "Yado Karu",
    "Muka Muka",
    "Dark Elf",
    "Lava Battleguard",
    "Electric Lizard",
    "Invitation to a Dark Sleep",
    "Panther Warrior",
    "Drill Bug",
    "Total Defense Shogun",
    "Flash Assailant",
    "Karate Man",
    "Boar Soldier",
    "Ceremonial Bell",
    "Kryuel",
    "Arsenal Bug",
    "Archfiend of Gilfer",
    "Dark Sage",
    "Byser Shock",
    "Ryu-Kishin Clown",
    "The Hunter with 7 Weapons",
    "Great Phantom Thief",
    "Blindly Loyal Goblin",
    "Emissary of the Oasis",
    "Familiar Knight",
    "Element Soldier",
    "Mind on Air",
    "Element Saurus",
    "Bone Mouse",
    "Yormungarde",
    "Pale Beast",
    "Ancient Lizard Warrior",
    "Red Archery Girl",
    "Grand Tiki Elder",
    "Melchid the Four-Face Beast",
    "Souls of the Forgotten",
    "The Portrait's Secret",
    "The Gross Ghost of Fled Dreams",
    "Headless Knight",
    "The Earl of Demise",
    "Gigobyte",
    "Fiend Scorpion",
    "Goblin Calligrapher"
  ],
  "pack": "first-effect-monster"
}



### Step Up Spell・Trap

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Last Will",
    "Confiscation",
    "Giant Trunade",
    "The Shallow Grave",
    "Soul Release",
    "Foolish Burial",
    "Reasoning",
    "Compulsory Evacuation Device",
    "Monster Gate",
    "Curse of Anubis",
    "Soul Resurrection",
    "Hallowed Life Barrier",
    "Time Machine",
    "Dark Magic Curtain",
    "Magical Hats",
    "Riryoku",
    "Shift",
    "Book of Taiyou",
    "Trap Dustshoot",
    "Monster Relief",
    "Clone Duplication",
    "Cost Down",
    "Tribute Doll",
    "Physical Double",
    "Big Burn",
    "Dark Mirror Force",
    "Desert Sunlight",
    "A Feather of the Phoenix",
    "Phoenix Wing Wind Blast",
    "Forced Ceasefire",
    "Rising Energy",
    "Big Evolution Pill",
    "Dimensionhole",
    "Thousand Knives",
    "Dark Magician's Tome of Black Magic",
    "Dark Spirit of the Silent",
    "Spiritualism",
    "Miracle Dig",
    "Rope of Life",
    "Disappear",
    "Reversal Quiz",
    "Interdimensional Matter Transporter",
    "Dark Core",
    "Thunder of Ruler",
    "Emblem of Dragon Destroyer",
    "Hidden Book of Spell",
    "Staunch Defender",
    "Frozen Soul",
    "D.D. Designator",
    "Dimension Distortion",
    "Chain Disappearance",
    "Ultra Evolution Pill",
    "Fiend's Hand Mirror",
    "Earthquake",
    "Earthbound Spirit's Invitation",
    "Sword of the Soul-Eater",
    "Dust Barrier",
    "Delta Attacker",
    "Human-Wave Tactics",
    "Abyssal Designator",
    "Taunt",
    "Mind Crush",
    "Level Conversion Lab",
    "Conscription",
    "Karma Cut",
    "Next to be Lost",
    "Hunting Instinct",
    "Tail Swipe"
  ],
  "pack": "step-up-spell・trap"
}



### Anti Effect

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Jinzo",
    "Heavy Storm",
    "Mystical Space Typhoon",
    "Skill Drain",
    "Skull Descovery Knight",
    "Royal Decree",
    "Dust Tornado",
    "Dark Balter the Terrible",
    "Ryu Senshi",
    "Tyrant Dragon",
    "Fiend Skull Dragon",
    "Calamity of the Wicked",
    "Spell Canceller",
    "Chiron the Mage",
    "The End of Anubis",
    "Alkana Knight Joker",
    "Big Shield Gardna",
    "Amplifier",
    "Nobleman of Extermination",
    "Royal Command",
    "Bait Doll",
    "Double Snare",
    "Swarm of Locusts",
    "Timidity",
    "Blade Knight",
    "Chaos Command Magician",
    "My Body as a Shield",
    "Invader of Darkness",
    "Rare Metalmorph",
    "Mid Shield Gardna",
    "Anteatereatingant",
    "Gorgon's Eye",
    "Remove Trap",
    "De-Spell",
    "Gust",
    "Driving Snow",
    "Armored Glass",
    "Mystic Probe",
    "Metal Detector",
    "The Emperor's Holiday",
    "Enchanted Arrow",
    "Twin-Headed Wolf",
    "Frontier Wiseman",
    "Magic Reflector",
    "Gora Turtle of Illusion",
    "Arcane Archer of the Forest",
    "Gemini Fiend",
    "Sorcerer of Dark Magic"
  ],
  "pack": "anti-effect"
}



### Life Breaker

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Dark Hole",
    "Torrential Tribute",
    "Lightning Vortex",
    "Exiled Force",
    "Tribe-Infecting Virus",
    "Macro Cosmos",
    "Acid Trap Hole",
    "Widespread Ruin",
    "Fissure",
    "Trap Hole",
    "Tribute to The Doomed",
    "Nobleman of Crossout",
    "Bottomless Trap Hole",
    "Bottomless Shifting Sand",
    "Needle Wall",
    "Sakuretsu Armor",
    "Smashing Ground",
    "Grand Convergence",
    "Chain Destruction",
    "Tragedy",
    "Michizure",
    "Mystic Box",
    "Blind Destruction",
    "Throwstone Unit",
    "Swarm of Scarabs",
    "Newdoria",
    "Rope of Spirit",
    "Roulette Barrel",
    "Soul Taker",
    "Hammer Shot",
    "D.D. Trap Hole",
    "Icarus Attack",
    "Jurassic World",
    "Volcanic Eruption",
    "Eradicating Aerosol",
    "Breath of Light",
    "Eternal Draught",
    "House of Adhesive Tape",
    "Eatgaboon",
    "Goblin Fan",
    "Two-Pronged Attack",
    "White Hole",
    "Earthshaker",
    "Return of the Doomed",
    "Infinite Dismissal",
    "Skull Lair",
    "Viser Des",
    "After the Struggle",
    "Needle Ceiling",
    "Pineapple Blast",
    "Assault on GHQ",
    "Medusa Worm",
    "Weed Out",
    "Generation Shift"
  ],
  "pack": "life-breaker"
}



### Go Go Direct

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Catapult Turtle",
    "Blast Sphere",
    "Airknight Parshath",
    "Magic Cylinder",
    "Cannon Soldier",
    "Exarion Universe",
    "Big Bang Shot",
    "Shooting Star Bow - Ceal",
    "Opti-Camouflage Armor",
    "Raging Flame Sprite",
    "Dimension Wall",
    "Rancer Dragonute",
    "Jinzo 7",
    "Gear Golem the Moving Fortress",
    "Ectoplasmer",
    "Fairy Meteor Crush",
    "Mad Sword Beast",
    "Spear Dragon",
    "Inaba White Rabbit",
    "Mefist the Infernal General",
    "Enraged Battle Ox",
    "Gaia Soul the Combustible Collective",
    "Castle Gate",
    "Shadowslayer",
    "Baby Dragon",
    "Mystic Lamp",
    "Leghul",
    "Ooguchi",
    "Rainbow Flower",
    "Queen's Double",
    "Alligator's Sword",
    "Alligator's Sword Dragon",
    "Mucus Yolk",
    "Servant of Catabolism",
    "Drillago",
    "Meteorain",
    "Mass Driver",
    "Dark Driceratops",
    "Black Tyranno",
    "Anti-Aircraft Flower",
    "Destruction Ring",
    "Bitelon",
    "Rocket Jumper",
    "Needle Burrower",
    "Atomic Firefly",
    "Piranha Army",
    "Man-Thro' Tro'",
    "Des Counterblow",
    "Absolute End",
    "Astral Barrier",
    "Mecha-Dog Marron",
    "Saber Beetle",
    "Sonic Shooter"
  ],
  "pack": "go-go-direct"
}

### Visitor from the Dark

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Crush Card Virus",
    "Don Zaloog",
    "Deck Devastation Virus",
    "Mystic Tomato",
    "Swift Gaia the Fierce Knight",
    "Cliff the Trap Remover",
    "Dark Scorpion - Meanae the Thorn",
    "Double Coston",
    "Pitch-Black Warwolf",
    "Fusilier Dragon, the Dual-Mode Beast",
    "D.D. Survivor",
    "La Jinn the Mystical Genie of the Lamp",
    "Mechanical Spider",
    "Vorse Raider",
    "8-Claws Scorpion",
    "Hidden Soldiers",
    "Dark Scorpion - Chick the Yellow",
    "Archfiend Soldier",
    "Dark Scorpion - Gorg the Strong",
    "Strike Ninja",
    "D.D. Scout Plane",
    "Mad Dog of Darkness",
    "Dark Dreadroute",
    "Horn Imp",
    "Koumori Dragon",
    "Trial of Nightmare",
    "Witty Phantom",
    "Lord of Zemia",
    "Fiend Sword",
    "Dark Titan of Terror",
    "Ancient Sorcerer",
    "Mystic Clown",
    "Cyber Soldier of Darkworld",
    "Sword of Dark Destruction",
    "Yaranzo",
    "Ryu-Kishin Powered",
    "Yaiba Robo",
    "Magical Ghost",
    "Brave Scizzar",
    "Ghoul with an Appetite",
    "Whiptail Crow",
    "Baron of the Fiend Sword",
    "Sorcerer of the Doomed",
    "Luminous Soldier",
    "The Illusory Gentleman",
    "Timeater",
    "Opticlops",
    "Dark Scorpion Burglars",
    "Gil Garth",
    "Mustering of the Dark Scorpions",
    "Dark Scorpion Combination",
    "Element Doom",
    "Chthonian Soldier",
    "D.D. Guide"
  ],
  "pack": "visitor-from-the-dark"
}

### Emergent Fire

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Manticore of Darkness",
    "Sacred Phoenix of Nephthys",
    "UFO Turtle",
    "Inferno",
    "Gren Maju Da Eiza",
    "Ultimate Baseball Kid",
    "Thestalos the Firestorm Monarch",
    "Flame Ruler",
    "Infernal Flame Emperor",
    "Blast Juggler",
    "Little Chimera",
    "Jigen Bakudan",
    "Rigras Leever",
    "Spirit of Flames",
    "Ultimate Obedient Fiend",
    "Battle Footballer",
    "Blazing Inpachi",
    "The Thing in the Crater",
    "Twinheaded Beast",
    "Backfire",
    "Charcoal Inpachi",
    "Horus' Servant",
    "Fox Fire",
    "Blazing Hiita",
    "Garoozis",
    "Fire Eye",
    "Launcher Spider",
    "Giga-Tech Wolf",
    "Fire Kraken",
    "Flame Cerberus",
    "Tyhone 2",
    "Salamandra",
    "Ryu-Ran",
    "Burning Spear",
    "Flame Champion",
    "Twin-Headed Fire Dragon",
    "Darkfire Soldier 1",
    "Mr. Volcano",
    "Darkfire Soldier #2",
    "Robotic Knight",
    "Molten Behemoth",
    "Flame Dancer",
    "Gadget Soldier",
    "Dokuroyaiba",
    "Lady Assailant of Flames",
    "Fire Sorcerer",
    "Great Angus",
    "Woodborg Inpachi",
    "Invasion of Flames",
    "Firebird",
    "Infernal Incinerator"],
  "pack": "emergent-fire"
}

### Water of Life

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Levia-Dragon - Daedalus",
    "Mobius the Frost Monarch",
    "Treeborn Frog",
    "Mother Grizzly",
    "Maiden of the Aqua",
    "A Legendary Ocean",
    "Gora Turtle",
    "Nightmare Penguin",
    "Fenrir",
    "Abyss Soldier",
    "Star Boy",
    "Serpentine Princess",
    "Tornado Wall",
    "Aqua Spirit",
    "Lord Poison",
    "Yomi Ship",
    "Gagagigo",
    "Giga Gagagigo",
    "Terrorking Salmon",
    "Amphibious Bugroth MK-3",
    "Orca Mega-Fortress of Darkness",
    "Salvage",
    "Unshaven Angler",
    "Ocean Dragon Lord - Neo-Daedalus",
    "Raging Eria",
    "Steel Shell",
    "Takriminos",
    "7 Colored Fish",
    "Crazy Fish",
    "Violent Rain",
    "High Tide Gyojin",
    "Fairy of the Fountain",
    "Deepsea Warrior",
    "Revival Jam",
    "Amphibian Beast",
    "The Legendary Fisherman",
    "Jam Defender",
    "Skull Mariner",
    "Kabazauls",
    "Lekunga",
    "Sea Serpent Warrior of Darkness",
    "Don Turtle",
    "Torpedo Fish",
    "Cannonball Spear Shellfish",
    "Mermaid Knight",
    "Big Wave Small Wave",
    "Creeping Doom Manta",
    "Des Frog",
    "T.A.D.P.O.L.E.",
    "Poison Draw Frog",
    "Des Croaking",
    "Beelze Frog",
    "Grass Phantom",
    "D.3.S. Frog"
  ],
  "pack": "water-of-life"
}

### Gift of Wind

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Slate Warrior",
    "The Tricky",
    "Black Ptera",
    "Flying Kamakiri #1",
    "Silpheed",
    "Insect Princess",
    "Hand of Nephthys",
    "Dreadscythe Slayer",
    "Swift Birdman Joe",
    "Bladefly",
    "Little-Winguard",
    "Sonic Jammer",
    "Garuda the Wind Spirit",
    "Tricky's Magic 4",
    "Whirlwind Prodigy",
    "Adhesive Explosive",
    "Whirlwind Weasel",
    "Storming Wynn",
    "Simorgh, Bird of Divinity",
    "Rallis the Star Bird",
    "Spirit of the Books",
    "Yamatano Dragon Scroll",
    "Djinn the Watcher of the Wind",
    "Kurama",
    "Dancing Elf",
    "Bat",
    "Sky Dragon",
    "Wing Eagle",
    "Queen Bird",
    "Air Eater",
    "Insect Soldiers of the Sky",
    "Peacock",
    "Monstrous Bird",
    "Winged Dragon, Guardian of the Fortress 2",
    "Crow Goblin",
    "Fiend Reflection 1",
    "Gust Fan",
    "Dark Bat",
    "Flying Kamakiri 2",
    "Flying Fish",
    "Girochin Kuwagata",
    "Bombardment Beetle",
    "4-Starred Ladybug of Doom",
    "The All-Seeing White Tiger",
    "Gray Wing",
    "Winged Sage Falcos",
    "Sonic Duck",
    "Nin-Ken Dog",
    "Chaosrider Gustaph",
    "Roc from the Valley of Haze",
    "Eagle Eye"
  ],
  "pack": "gift-of-wind"
}

### Platinum Light

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Zaborg the Thunder Monarch",
    "Elemental Mistress Doriado",
    "Golden Homunculus",
    "Reflect Bounder",
    "Shining Angel",
    "Freed the Brave Wanderer",
    "Ninja Grandmaster Sasuke",
    "The Creator",
    "Batteryman AA",
    "Helios Tris Megistus",
    "Super Conductor Tyranno",
    "Hoshiningen",
    "Soul of Purity and Light",
    "Kaiser Sea Horse",
    "Gilford the Lightning",
    "Mystical Knight of Jackal",
    "Emes the Infinity",
    "Andro Sphinx",
    "Sphinx Teleia",
    "Theinen the Great Sphinx",
    "The Creator Incarnate",
    "Battery Charger",
    "Helios Duo Megistus",
    "Super-Electromagnetic Voltech Dragon",
    "Oscillo Hero 2",
    "Fiend Reflection 2",
    "Ray & Temperature",
    "Dark Artist",
    "Elf's Light",
    "Binding Chain",
    "Shining Friendship",
    "Maiden of the Moonlight",
    "Bright Castle",
    "Dunames Dark Witch",
    "Wingweaver",
    "Bio-Mage",
    "Dreamsprite",
    "Queen's Knight",
    "King's Knight",
    "Jack's Knight",
    "Ray of Hope",
    "Teva",
    "Solar Ray",
    "Beckoning Light",
    "Pyramid of Light",
    "Element Magician",
    "Homunculus the Alchemic Being",
    "Element Valkyrie",
    "Doriado's Blessing",
    "Batteryman C",
    "Helios - The Primordial Sun",
    "Batteryman D"
  ],
  "pack": "platinum-light"
}

### Earth Dwellers

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Guardian Sphinx",
    "Megarock Dragon",
    "Tyranno Infinity",
    "Stone Statue of the Aztecs",
    "Giant Rat",
    "Marauding Captain",
    "Gigantes",
    "Master Monk",
    "Doom Dozer",
    "Black Stego",
    "Ultimate Tyranno",
    "Milus Radiant",
    "Gemini Elf",
    "Goblin Attack Force",
    "The Rock Spirit",
    "Gilasaurus",
    "Maximum Six",
    "Legendary Jujitsu Master",
    "Howling Insect",
    "The Trojan Horse",
    "Insect Knight",
    "Golem Sentry",
    "Hieracosphinx",
    "Criosphinx",
    "Gilford the Legend",
    "Exxod, Master of The Guard",
    "Avalanching Aussa",
    "Axe Raider",
    "Invigoration",
    "Cobraman Sakuzy",
    "Neo Bug",
    "Disc Fighter",
    "Legacy Hunter",
    "Ghost Knight of Jackal",
    "Enraged Muka Muka",
    "Blockman",
    "Chu-Ske the Mouse Fighter",
    "Granmarg the Rock Monarch",
    "Millennium Scorpion",
    "Lost Guardian",
    "Grave Ohja",
    "Mine Golem",
    "Monk Fighter",
    "Guardian Statue",
    "Kaminote Blow",
    "Legendary Black Belt",
    "Minefield Eruption",
    "Rock Bombardment",
    "Jerry Beans Man",
    "Parasitic Ticky",
    "Gokipon",
    "Sand Moth",
    "Great Spirit",
    "Miracle Jurassic Egg",
    "Babycerasaurus"
  ],
  "pack": "earth-dwellers"
}

### Endless Thoughts

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Call of the Haunted",
    "Gravity Bind",
    "Spell Economics",
    "Kunai with Chain",
    "Shadow Spell",
    "Chain Energy",
    "The Eye of Truth",
    "Mask of Dispel",
    "Convulsion of Nature",
    "Spirit Barrier",
    "Toll",
    "Chorus of Sanctuary",
    "Skull Invitation",
    "Anti-Spell Fragrance",
    "Burning Land",
    "Graverobber's Retribution",
    "Vengeful Bog Spirit",
    "Blast with Chain",
    "Archfiend's Oath",
    "Stumbling",
    "DNA Transplant",
    "Swords of Concealing Light",
    "Forest",
    "Wasteland",
    "Mountain",
    "Sogen",
    "Umi",
    "Yami",
    "Spellbinding Circle",
    "Insect Barrier",
    "World Suppression",
    "The Regulation of Tribe",
    "Respect Play",
    "Inspection",
    "Aqua Chorus",
    "Jam Breeding Machine",
    "Infinite Cards",
    "Type Zero Magic Crusher",
    "Yellow Luster Shield",
    "Card Shuffle",
    "Banner of Courage",
    "Kishido Spirit",
    "Senri Eye",
    "D.D. Borderline",
    "Recycle",
    "Robbin' Zombie",
    "Ninjitsu Art of Transformation",
    "Labyrinth of Nightmare",
    "Two-Man Cell Battle",
    "Ninjitsu Art of Decoy",
    "Enervating Mist",
    "Shattered Axe",
    "Shifting Shadows",
    "Impenetrable Formation",
    "Prepare to Strike Back"
  ],
  "pack": "endless-thoughts"
}

### Flip the Picture

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [ "Mask of Darkness",
    "Morphing Jar",
    "Cyber Jar",
    "Magician of Faith",
    "Penguin Soldier",
    "Spear Cretin",
    "Morphing Jar #2",
    "Magical Merchant",
    "Night Assailant",
    "Man-Eater Bug",
    "Skelengel",
    "Needle Worm",
    "Greenkappa",
    "Hiro's Shadow Scout",
    "Jowls of Dark Demise",
    "Electromagnetic Bagworm",
    "Mysterious Guard",
    "Des Feral Imp",
    "Dice Jar",
    "Old Vindictive Magician",
    "Nobleman-Eater Bug",
    "Searchlightman",
    "Reaper of the Cards",
    "Big Eye",
    "Trap Master",
    "Princess of Tsurugi",
    "The Immortal of Thunder",
    "Armed Ninja",
    "Needle Ball",
    "Hane-Hane",
    "Weather Report",
    "Invader of the Throne",
    "Dark-Eyes Illusionist",
    "Parasite Paracide",
    "Bite Shoes",
    "The Stern Mystic",
    "Tornado Bird",
    "Poison Mummy",
    "Cobra Jar",
    "Dimension Jar",
    "Dark Cat with White Tail",
    "Crimson Ninja",
    "Gale Lizard",
    "Witch Doctor of Chaos",
    "Spirit Caller",
    "Rafflesia Seduction",
    "Hade-Hane",
    "Brain Jacker",
    "Dummy Golem",
    "White Ninja",
    "Guard Dog"
  ],
  "pack": "flip-the-picture"
}

### Equip Me

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Axe of Despair",
    "Megamorph",
    "Premature Burial",
    "Maha Vailo",
    "Gravity Axe - Grarl",
    "Wicked-Breaking Flamberge - Baou",
    "Twin Swords of Flashing Light - Tryce",
    "Iron Blacksmith Kotetsu",
    "Armed Samurai - Ben Kei",
    "Black Pendant",
    "Malevolent Nuzzler",
    "Ring of Magnetism",
    "Mask of Brutality",
    "Scroll of Bewitchment",
    "Collected Power",
    "Ekibyo Drakmord",
    "Heart of Clear Water",
    "Demotion",
    "Autonomous Action Unit",
    "Raregold Armor",
    "Fairy of the Spring",
    "Fuhma Shuriken",
    "Flint",
    "Mistobody",
    "Laser Cannon Armor",
    "Insect Armor with Laser Cannon",
    "Vile Germs",
    "Horn of Light",
    "Horn of the Unicorn",
    "Electro-Whip",
    "Mystical Moon",
    "Raise Body Heat",
    "Follow Wind",
    "Power of Kaishin",
    "Eternal Rest",
    "Cyber Raider",
    "Sword of Deep-Seated",
    "Germ Infection",
    "Paralyzing Potion",
    "Stim-Pack",
    "Tailor of the Fickle",
    "Woodland Sprite",
    "Smoke Grenade of the Thief",
    "Buster Rancher",
    "Disarmament",
    "Arsenal Summoner",
    "Guardian Elma",
    "Guardian Ceal",
    "Guardian Grarl",
    "Guardian Baou",
    "Guardian Kay'est",
    "Guardian Tryce",
    "Rod of Silence - Kay'est",
    "Rod of the Mind's Eye",
    "Arsenal Robber",
    "Really Eternal Rest",
    "Ballista of Rampart Smashing",
    "Nitro Unit",
    "Symbol of Heritage"
  ],
  "pack": "equip-me"
}

### More Eternal Memories

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Destiny Board",
    "Cathedral of Nobles",
    "Level Limit - Area B",
    "Ultimate Offering",
    "Messenger of Peace",
    "Ground Collapse",
    "Ordeal of a Traveler",
    "Metal Reflect Slime",
    "Spatial Collapse",
    "Skull Zoma",
    "Wall of Revealing Light",
    "Robbin' Goblin",
    "DNA Surgery",
    "Light of Intervention",
    "Mirror Wall",
    "Mask of Restrict",
    "Fairy Box",
    "Embodiment of Apophis",
    "Second Coin Toss",
    "Terraforming",
    "Final Attack Orders",
    "Non-Spellcasting Area",
    "Dangerous Machine TYPE-6",
    "Level Limit - Area A",
    "Silent Insect",
    "Magical Thorn",
    "Gravekeeper's Servant",
    "Gaia Power",
    "Umiiruka",
    "Molten Destruction",
    "Rising Air Current",
    "Luminous Spark",
    "Mystic Plasma Zone",
    "Forced Requisition",
    "Minor Goblin Official",
    "Prohibition",
    "Spirit Message \"I\"",
    "Spirit Message \"N\"",
    "Spirit Message \"A\"",
    "Spirit Message \"L\"",
    "Fatal Abacus",
    "Array of Revealing Light",
    "Different Dimension Gate",
    "Tower of Babel",
    "Curse of Darkness",
    "Nubian Guard",
    "Malice Doll of Demise",
    "Lighten the Load",
    "Malice Dispersion",
    "Xing Zhen Hu",
    "Chain Burst",
    "Spell Purification",
    "Canyon",
    "Elemental Absorber",
    "Dimensional Fissure",
    "Seismic Shockwave"
  ],
  "pack": "more-eternal-memories"
}

### Speed King

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Solemn Judgment",
    "Book of Moon",
    "Seven Tools of the Bandit",
    "Judgment of Anubis",
    "Cursed Seal of the Forbidden Spell",
    "Divine Wrath",
    "Dark Ruler Vandalgyon",
    "Voltanis the Adjudicator",
    "Magic Jammer",
    "Shrink",
    "Barrel Behind the Door",
    "Spell Shield Type-8",
    "Trap Jammer",
    "Triage",
    "Bountiful Artemis",
    "Forced Back",
    "Negate Attack",
    "Multiply",
    "Graceful Dice",
    "Horn of Heaven",
    "Rush Recklessly",
    "The Reliable Guardian",
    "Magic Drain",
    "Riryoku Field",
    "Pyramid Energy",
    "Tutan Mask",
    "Curse of Royal",
    "Spell of Pain",
    "Trap of Board Eraser",
    "Pigeonholing Books of Spell",
    "Spell Vanishing",
    "Dedication through Light and Darkness",
    "Armor Break",
    "Soul Reversal",
    "Serial Spell",
    "Spell-Stopping Statute",
    "Royal Surrender",
    "Goblin Out of the Frying Pan",
    "Malfunction",
    "Layard the Liberator",
    "Synthetic Seraphim"
  ],
  "pack": "speed-king"
}

### Spice of Duel

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Toon Cannon Soldier",
    "Tsukuyomi",
    "VWXYZ-Dragon Catapult Cannon",
    "Toon Summoned Skull",
    "Toon World",
    "Hino-Kagu-Tsuchi",
    "Asura Priest",
    "Toon Table of Contents",
    "XYZ-Dragon Cannon",
    "Corpse of Yata-Garasu",
    "Heavy Mech Support Platform",
    "Yamata Dragon",
    "Dark Dust Spirit",
    "Toon Dark Magician Girl",
    "Toon Gemini Elf",
    "Toon Goblin Attack Force",
    "X-Head Cannon",
    "Y-Dragon Head",
    "XY-Dragon Cannon",
    "Z-Metal Tank",
    "Giant Orc",
    "XZ-Tank Cannon",
    "YZ-Tank Dragon",
    "Indomitable Fighter Lei Lei",
    "Roll Out!",
    "Manga Ryu-Ran",
    "Toon Mermaid",
    "Blue-Eyes Toon Dragon",
    "Maharaghi",
    "Susa Soldier",
    "Great Long Nose",
    "Otohime",
    "Fushi No Tori",
    "Fengsheng Mirror",
    "Spiritual Energy Settle Machine",
    "Spirit's Invitation",
    "Toon Defense",
    "Toon Masked Sorcerer",
    "Dark Blade",
    "Pitch-Dark Dragon",
    "Kiryu",
    "Decayed Commander",
    "Zombie Tiger",
    "Second Goblin",
    "Vampire Orchis",
    "Des Dendle",
    "Burning Beast",
    "Freezing Beast",
    "Union Rider",
    "Frontline Base",
    "Combination Attack",
    "Formation Union",
    "Metallizing Parasite - Lunatite",
    "Dark Blade the Dragon Knight",
    "Protective Soul Ailin",
    "V-Tiger Jet",
    "W-Wing Catapult",
    "VW-Tiger Catapult"
  ],
  "pack": "spice-of-duel"
}

### Fairy's Sky

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "The Sanctuary in the Sky",
    "Marshmallon",
    "Banisher of the Radiance",
    "Banisher of the Light",
    "Kelbek",
    "Begone, Knave!",
    "The Agent of Judgment - Saturn",
    "Archlord Zerato",
    "Majestic Mech - Goryu",
    "Celestial Transformation",
    "Kotodama",
    "Moisture Creature",
    "Mystical Beast Serket",
    "Mudora",
    "Cestus of Dagla",
    "Watapon",
    "Majestic Mech - Ohka",
    "Herald of Purple Light",
    "Herald of Green Light",
    "Miraculous Descent",
    "Spirit of the Harp",
    "Key Mace",
    "Happy Lover",
    "Hourglass of Life",
    "Wing Egg Elf",
    "Silver Bow and Arrow",
    "Goddess of Whim",
    "Dark Witch",
    "Muse-A",
    "Tenderness",
    "Hourglass of Courage",
    "Winged Egg of New Life",
    "Shining Abyss",
    "The Forgiving Maiden",
    "St. Joan",
    "Keldo",
    "Agido",
    "Warrior of Zera",
    "Mystical Shine Ball",
    "The Agent of Wisdom - Mercury",
    "The Agent of Creation - Venus",
    "The Agent of Force - Mars",
    "Light of Judgment",
    "Marshmallon glasses",
    "Mokey Mokey",
    "Mokey Mokey King",
    "Mokey Mokey Smackdown",
    "Majestic Mech - Senku"
  ],
  "pack": "fairy's-sky"
}

### Dragon Drive

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "F.G.D.",
    "Dragon's Mirror",
    "White Horns D.",
    "Meteor B. Dragon",
    "Stamping Destruction",
    "Kaiser Glider",
    "Des Volstgalph",
    "Master of Dragon Soldier",
    "Masked Dragon",
    "Mirage Dragon",
    "Twin-Headed Behemoth",
    "Spirit Ryu",
    "The Dragon dwelling in the Cave",
    "Troop Dragon",
    "Dragon's Rage",
    "Blue-Eyes Shining Dragon",
    "Red-Eyes B. Chick",
    "Red-Eyes Darkness Dragon",
    "Axe Dragonute",
    "Gaia the Dragon Champion",
    "Dragon Piper",
    "Thousand Dragon",
    "Crawling Dragon",
    "B. Skull Dragon",
    "Wicked Dragon with the Ersatz Head",
    "Dragon Treasure",
    "Dragon Capture Jar",
    "Parrot Dragon",
    "Dragon Seeker",
    "B. Dragon Jungle King",
    "Meteor Dragon",
    "Dragonic Attack",
    "Warrior Dai Grepher",
    "Dragon Manipulator",
    "Lizard Soldier",
    "Cave Dragon",
    "The Dragon's Bead",
    "A Wingbeat of Giant Dragon",
    "Dragon's Gunfire",
    "Super Rejuvenation",
    "Burst Breath",
    "D. Tribe",
    "Rare Metal Dragon",
    "Element Dragon",
    "Divine Dragon - Excelion"
  ],
  "pack": "dragon-drive"
}

### Fiend Night

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Dark Ruler Ha Des",
    "Great Maju Garzett",
    "Skull Archfiend of Lightning",
    "Dark Necrofear",
    "Legendary Fiend",
    "Terrorking Archfiend",
    "Pandemonium",
    "Goblin King",
    "Goldd, Wu-Lord of Dark World",
    "Dark World Lightning",
    "Lesser Fiend",
    "Possessed Dark Soul",
    "Infernalqueen Archfiend",
    "Falling Down",
    "Mazera DeVille",
    "Emissary of the Afterlife",
    "Goblin Elite Attack Force",
    "Brron, Mad King of Dark World",
    "Sillva, Warlord of Dark World",
    "Gateway to Dark World",
    "Dark Energy",
    "The Cheerful Coffin",
    "Exile of the Wicked",
    "Winged Minion",
    "Skull Knight #2",
    "Bark of Dark Ruler",
    "The Puppet Magic of Dark Ruler",
    "Soul Demolition",
    "Puppet Master",
    "Helpoemer",
    "Maju Garzett",
    "Pandemonium Watchbear",
    "Goblin of Greed",
    "Vilepawn Archfiend",
    "Shadowknight Archfiend",
    "Darkbishop Archfiend",
    "Desrook Archfiend",
    "Checkmate",
    "Battle-Scarred",
    "Archfiend's Roar",
    "Inferno Hammer",
    "Kozaky",
    "Theban Nightmare",
    "Aswan Apparition",
    "Grave Protector",
    "Giant Kozaky",
    "Zure, Knight of Dark World",
    "Beiige, Vanguard of Dark World",
    "Broww, Huntsman of Dark World",
    "Scarr, Scout of Dark World",
    "The Forces of Darkness",
    "Dark Deal"
  ],
  "pack": "fiend-night"
}

### Skillful Spellcasters

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Jowgen the Spiritualist",
    "Chaos Sorcerer",
    "Dark Magician of Chaos",
    "Gravekeeper's Spy",
    "Necrovalley",
    "Skilled Dark Magician",
    "Apprentice Magician",
    "Magical Dimension",
    "Magician's Circle",
    "Summon Priest",
    "Kycoo the Ghost Destroyer",
    "Gravekeeper's Spear Soldier",
    "Gravekeeper's Chief",
    "A Cat of Ill Omen",
    "Royal Tribute",
    "Diffusion Wave-Motion",
    "Magical Marionette",
    "Magician's Valkyria",
    "Blast Magician",
    "D.D.M. - Different Dimension Master",
    "Dryad",
    "Book of Secret Arts",
    "Hannibal Necromancer",
    "Last Day of Witch",
    "Gravekeeper's Curse",
    "Gravekeeper's Guard",
    "Gravekeeper's Vassal",
    "Gravekeeper's Watcher",
    "Gravekeeper's Cannonholder",
    "Gravekeeper's Assailant",
    "A Man with Wdjat",
    "An Owl of Luck",
    "Charm of Shabti",
    "Rite of Spirit",
    "Skilled White Magician",
    "Pixie Knight",
    "Magical Plant Mandragola",
    "Armor Exe",
    "Pitch-Black Power Stone",
    "Mega Ton Magical Cannon",
    "Exhausting Spell",
    "Miracle Restoring",
    "Anti-Spell",
    "Sand Gambler",
    "Peten the Dark Clown",
    "Magician's Unite",
    "Mythical Beast Cerberus",
    "Magical Blast",
    "Toy Magician"
  ],
  "pack": "skillful-spellcasters"
}

### Cold Skin

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Vampire Lord",
    "Pyramid Turtle",
    "Book of Life",
    "Des Lacooda",
    "Spirit Reaper",
    "Berserk Dragon",
    "Ryu Kokki",
    "Soul-Absorbing Bone Tower",
    "Overpowering Eye",
    "King of the Skull Servants",
    "Patrician of Darkness",
    "Royal Keeper",
    "Great Dezard",
    "Fushioh Richie",
    "Call of the Mummy",
    "Reaper on the Nightmare",
    "Fear from the Dark",
    "Spirit of the Pharaoh",
    "The First Sarcophagus",
    "Vampire Genesis",
    "Skull Servant",
    "Castle of Dark Illusions",
    "Clown Zombie",
    "Pumpking the King of Ghosts",
    "Fiend's Hand",
    "Fire Reaper",
    "Mech Mole Zombie",
    "Phantom Ghost",
    "Violet Crystal",
    "Shadow Ghoul",
    "The Wandering Doomed",
    "Red-Moon Baby",
    "Wandering Mummy",
    "Giant Axe Mummy",
    "Gernia",
    "Nightmare Horse",
    "Goblin Zombie",
    "Despair from the Dark",
    "A Deal with Dark Ruler",
    "Chopman the Desperate Outlaw",
    "The Kick Man",
    "Vampire Lady",
    "Return Zombie",
    "Pharaoh's Servant",
    "Regenerating Mummy",
    "The Third Sarcophagus",
    "The Second Sarcophagus",
    "Blood Sucker",
    "Reborn Zombie",
    "Malice Ascendant"
  ],
  "pack": "cold-skin"
}

### Ritual Dance

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Shinato, King of a Higher Plane",
    "Dark Master - Zorc",
    "Demise, King of Armageddon",
    "The Masked Beast",
    "Legendary Flame Lord",
    "Contract with the Abyss",
    "Manju of the Ten Thousand Hands",
    "Earth Chant",
    "Reshef the Dark Being",
    "Ruin, Queen of Oblivion",
    "Senju of the Thousand Hands",
    "Sonic Bird",
    "Curse of the Masked Beast",
    "Paladin of White Dragon",
    "Shinato's Ark",
    "Incandescent Ordeal",
    "Contract with the Dark Master",
    "Fulfillment of the Contract",
    "Final Ritual of the Ancients",
    "End of the World",
    "Super War-Lion",
    "Zera The Mant",
    "Fiend's Mirror",
    "Zera Ritual",
    "War-Lion Ritual",
    "Beastly Mirror Ritual",
    "Commencement Dance",
    "Hamburger Recipe",
    "Novox's Prayer",
    "Turtle Oath",
    "Resurrection of Chakra",
    "Javelin Beetle Pact",
    "Garma Sword Oath",
    "Revival of Dokurorider",
    "Fortress Whale's Oath",
    "Performance of Sword",
    "Hungry Burger",
    "Skull Guardian",
    "Chakra",
    "Crab Turtle",
    "Garma Sword",
    "Javelin Beetle",
    "Fortress Whale",
    "Dokurorider",
    "White Dragon Ritual",
    "Ritual Weapon",
    "Samsara"
  ],
  "pack": "ritual-dance"
}

### Wave of the Future

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
    "Dandylion",
    "Chimeratech Overdragon",
    "Destiny Hero - Dasher",
    "Overload Fusion",
    "Phantom Beast Rock Lizard",
    "Elemental Hero Shining Phoenix Enforcer",
    "Destiny Hero - Diamond Dude",
    "Clock Tower Prison",
    "Destiny Hero - Double Dude",
    "Mausoleum of the Emperor",
    "Phantom Beast Cross-Wing",
    "Phantom Beast Wild-Horn",
    "Phantom Beast Thunder-Pegasus",
    "Elemental Hero Phoenix Enforcer",
    "Destiny Hero - Dreadmaster",
    "Destiny Signal",
    "D - Shield",
    "Destiny Hero - Fear Monger",
    "Destiny Hero - Dogma",
    "Dark City",
    "Elemental Hero Aqua Neos",
    "Elemental Hero Flare Neos",
    "Neo-Spacian Aqua Dolphin",
    "Neo Space",
    "Sabersaurus",
    "Alien Mother",
    "Cosmic Horror Gangi'el",
    "Crop Circles",
    "Elemental Hero Neos",
    "Destiny Hero - Doom Lord",
    "Destiny Hero - Captain Tenacious",
    "Misfortune",
    "D - Time",
    "Destiny Hero - Blade Master",
    "Destiny Hero - Defender",
    "D - Chain",
    "D - Spirit",
    "Destiny Mirage",
    "Chrysalis Dolphin",
    "Neo-Spacian Flare Scarab",
    "Contact",
    "Fake Hero",
    "Common Soul",
    "Spell Calling",
    "Alien Grey",
    "Alien Skull",
    "Alien Hunter",
    "Alien Warrior",
    "Flying Saucer Muusik'i",
    "Orbital Bombardment",
    "Brainwashing Beam",
    "Cyclone Blade"
  ],
  "pack": "wave-of-the-future"
}

### Hero Emerges!

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
  ],
  "pack": "hero-emerges"
}

###

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
  ],
  "pack": ""
}

###

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
  ],
  "pack": ""
}

###

POST http://localhost:3001/cards
Content-Type: application/json

{
  "names": [
  ],
  "pack": ""
}